BEGIN
    EXECUTE IMMEDIATE 'DROP TABLE ADMIN.task_cover CASCADE CONSTRAINTS'; EXCEPTION WHEN OTHERS THEN IF SQLCODE != -942 THEN RAISE; END IF; END;
/
BEGIN
    EXECUTE IMMEDIATE 'DROP TABLE ADMIN.task_attachement CASCADE CONSTRAINTS'; EXCEPTION WHEN OTHERS THEN IF SQLCODE != -942 THEN RAISE; END IF; END;
/
BEGIN
    EXECUTE IMMEDIATE 'DROP TABLE ADMIN.task_assignee CASCADE CONSTRAINTS'; EXCEPTION WHEN OTHERS THEN IF SQLCODE != -942 THEN RAISE; END IF; END;
/
BEGIN
    EXECUTE IMMEDIATE 'DROP TABLE ADMIN.stage_task CASCADE CONSTRAINTS'; EXCEPTION WHEN OTHERS THEN IF SQLCODE != -942 THEN RAISE; END IF; END;
/
BEGIN
    EXECUTE IMMEDIATE 'DROP TABLE ADMIN.student_board CASCADE CONSTRAINTS'; EXCEPTION WHEN OTHERS THEN IF SQLCODE != -942 THEN RAISE; END IF; END;
/
BEGIN
    EXECUTE IMMEDIATE 'DROP TABLE ADMIN.student CASCADE CONSTRAINTS'; EXCEPTION WHEN OTHERS THEN IF SQLCODE != -942 THEN RAISE; END IF; END;
/
BEGIN
    EXECUTE IMMEDIATE 'DROP TABLE ADMIN.stage CASCADE CONSTRAINTS'; EXCEPTION WHEN OTHERS THEN IF SQLCODE != -942 THEN RAISE; END IF; END;
/
BEGIN
    EXECUTE IMMEDIATE 'DROP TABLE ADMIN.quarter_group CASCADE CONSTRAINTS'; EXCEPTION WHEN OTHERS THEN IF SQLCODE != -942 THEN RAISE; END IF; END;
/
BEGIN
    EXECUTE IMMEDIATE 'DROP TABLE ADMIN.manager CASCADE CONSTRAINTS'; EXCEPTION WHEN OTHERS THEN IF SQLCODE != -942 THEN RAISE; END IF; END;
/
BEGIN
    EXECUTE IMMEDIATE 'DROP TABLE ADMIN.file_source CASCADE CONSTRAINTS'; EXCEPTION WHEN OTHERS THEN IF SQLCODE != -942 THEN RAISE; END IF; END;
/
BEGIN
    EXECUTE IMMEDIATE 'DROP TABLE ADMIN."FILE" CASCADE CONSTRAINTS'; EXCEPTION WHEN OTHERS THEN IF SQLCODE != -942 THEN RAISE; END IF; END;
/
BEGIN
    EXECUTE IMMEDIATE 'DROP TABLE ADMIN.COLOR CASCADE CONSTRAINTS'; EXCEPTION WHEN OTHERS THEN IF SQLCODE != -942 THEN RAISE; END IF; END;
/
BEGIN
    EXECUTE IMMEDIATE 'DROP TABLE ADMIN.board_stage CASCADE CONSTRAINTS'; EXCEPTION WHEN OTHERS THEN IF SQLCODE != -942 THEN RAISE; END IF; END;
/
BEGIN
    EXECUTE IMMEDIATE 'DROP TABLE ADMIN.board CASCADE CONSTRAINTS'; EXCEPTION WHEN OTHERS THEN IF SQLCODE != -942 THEN RAISE; END IF; END;
/
BEGIN
    EXECUTE IMMEDIATE 'DROP TABLE ADMIN.app_user CASCADE CONSTRAINTS'; EXCEPTION WHEN OTHERS THEN IF SQLCODE != -942 THEN RAISE; END IF; END;
/
BEGIN
    EXECUTE IMMEDIATE 'DROP TABLE ADMIN.admin CASCADE CONSTRAINTS'; EXCEPTION WHEN OTHERS THEN IF SQLCODE != -942 THEN RAISE; END IF; END;
/
BEGIN
    EXECUTE IMMEDIATE 'DROP TABLE ADMIN.academic_quarter CASCADE CONSTRAINTS'; EXCEPTION WHEN OTHERS THEN IF SQLCODE != -942 THEN RAISE; END IF; END;
/
BEGIN
    EXECUTE IMMEDIATE 'DROP TABLE ADMIN.academic_group CASCADE CONSTRAINTS'; EXCEPTION WHEN OTHERS THEN IF SQLCODE != -942 THEN RAISE; END IF; END;
/
BEGIN
    EXECUTE IMMEDIATE 'DROP TABLE ADMIN.task CASCADE CONSTRAINTS'; EXCEPTION WHEN OTHERS THEN IF SQLCODE != -942 THEN RAISE; END IF; END;
/
