-- Generated by Oracle SQL Developer Data Modeler 24.3.1.347.1153
--   at:        2025-06-27 17:02:42 CST
--   site:      Oracle Database 21c
--   type:      Oracle Database 21c



-- predefined type, no DDL - MDSYS.SDO_GEOMETRY

-- predefined type, no DDL - XMLTYPE

CREATE TABLE ADMIN.academic_group (
                                NAME CHAR(1 CHAR) NOT NULL
);

ALTER TABLE ADMIN.academic_group ADD CONSTRAINT academic_groups_pk PRIMARY KEY ( NAME );

CREATE TABLE ADMIN.academic_quarter (
                                  "number" INTEGER NOT NULL
);

ALTER TABLE ADMIN.academic_quarter ADD CONSTRAINT aqr_pk PRIMARY KEY ( "number" );

CREATE TABLE ADMIN.admin (
                       email VARCHAR2(63 CHAR) NOT NULL
);

ALTER TABLE ADMIN.admin ADD CONSTRAINT admins_pk PRIMARY KEY ( email );

CREATE TABLE ADMIN.app_user (
                          email      VARCHAR2(63 CHAR) NOT NULL,
                          password   VARCHAR2(255 CHAR),
                          verified   NUMBER DEFAULT 0 NOT NULL,
                          created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL,
                          updated_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL,
                          active     number DEFAULT 1 NOT NULL,
                          type       VARCHAR2(15) NOT NULL
);

CREATE OR REPLACE TRIGGER ADMIN.trg_update_timestamp
    BEFORE UPDATE ON ADMIN.app_user
    FOR EACH ROW
BEGIN
    :NEW.updated_at := CURRENT_TIMESTAMP;
END;
/

ALTER TABLE ADMIN.app_user
    ADD CONSTRAINT fkarc_1_lov
        CHECK ( type IN ( 'student', 'manager', 'admin' ) );

ALTER TABLE ADMIN.app_user ADD CONSTRAINT app_users_pk PRIMARY KEY ( email );

CREATE TABLE ADMIN.board (
                       title      VARCHAR2(63) NOT NULL,
                       mnr_email  VARCHAR2(63 CHAR) NOT NULL
);

ALTER TABLE ADMIN.board ADD CONSTRAINT boards_pk PRIMARY KEY ( mnr_email );

CREATE TABLE ADMIN.board_stage (
                             bad_email VARCHAR2(63 CHAR) NOT NULL,
                             sae_NAME  VARCHAR2(15 CHAR) NOT NULL
);

ALTER TABLE ADMIN.board_stage ADD CONSTRAINT board_stages_pk PRIMARY KEY ( bad_email,
                                                                     sae_NAME );

CREATE TABLE ADMIN.COLOR (
                       NAME VARCHAR2(15) NOT NULL,
                       CODE VARCHAR2(7) NOT NULL
);

ALTER TABLE ADMIN.COLOR ADD CONSTRAINT COLORs_pk PRIMARY KEY ( NAME );

CREATE TABLE ADMIN."FILE" (
                        id       RAW(16) NOT NULL,
                        NAME     VARCHAR2(63) NOT NULL,
                        mimetype VARCHAR2(31 CHAR) NOT NULL,
                        active     number DEFAULT 1 NOT NULL,
                        purpose  VARCHAR2(15) NOT NULL
);

ALTER TABLE ADMIN."FILE"
    ADD CONSTRAINT fkarc_2_lov CHECK ( purpose IN ( 'cover', 'attachement' ) );

ALTER TABLE ADMIN."FILE" ADD CONSTRAINT files_pk PRIMARY KEY ( id );

CREATE TABLE ADMIN.file_source (
                             fle_id RAW(16) NOT NULL,
                             source BLOB NOT NULL
);

ALTER TABLE ADMIN.file_source ADD CONSTRAINT file_sources_pk PRIMARY KEY ( fle_id );

CREATE TABLE ADMIN.manager (
                         email      VARCHAR2(63 CHAR) NOT NULL,
                         created_by VARCHAR2(63 CHAR) NOT NULL
);

ALTER TABLE ADMIN.manager ADD CONSTRAINT managers_pk PRIMARY KEY ( email );

CREATE TABLE ADMIN.quarter_group (
                               agp_NAME   CHAR(1 CHAR) NOT NULL,
    aqr_number INTEGER NOT NULL
);

ALTER TABLE ADMIN.quarter_group ADD CONSTRAINT quarter_groups_pk PRIMARY KEY ( agp_NAME,
                                                                         aqr_number );

CREATE TABLE ADMIN.stage (
                       NAME  VARCHAR2(15 CHAR) NOT NULL,
                       final NUMBER NOT NULL
);

ALTER TABLE ADMIN.stage ADD CONSTRAINT stages_pk PRIMARY KEY ( NAME );

CREATE TABLE ADMIN.stage_task (
                            "order"       NUMBER(10, 4) NOT NULL,
                            bse_bad_email VARCHAR2(63 CHAR) NOT NULL,
                            bse_sae_NAME  VARCHAR2(15 CHAR) NOT NULL,
                            tsk_id        RAW(16) NOT NULL
);

CREATE UNIQUE INDEX stage_tasks__idx ON
    ADMIN.stage_task (
                tsk_id
                ASC );

CREATE UNIQUE INDEX order__idx ON
    ADMIN.stage_task (
                "order", bse_bad_email, bse_sae_NAME
                ASC );

ALTER TABLE ADMIN.stage_task
    ADD CONSTRAINT stage_tasks_pk PRIMARY KEY ( bse_bad_email,
                                                bse_sae_NAME,
                                                tsk_id );

CREATE TABLE ADMIN.student (
                         email          VARCHAR2(63 CHAR) NOT NULL,
                         first_NAME     VARCHAR2(63) NOT NULL,
                         last_NAME      VARCHAR2(63) NOT NULL,
                         created_by     VARCHAR2(63 CHAR) NOT NULL,
                         qgp_agp_NAME   CHAR(1 CHAR) NOT NULL,
    qgp_aqr_number INTEGER NOT NULL
);

ALTER TABLE ADMIN.student ADD CONSTRAINT students_pk PRIMARY KEY ( email );

CREATE TABLE ADMIN.student_board (
                               issued_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL,
                               sdt_email VARCHAR2(63 CHAR) NOT NULL,
                               bad_email VARCHAR2(63 CHAR) NOT NULL
);

ALTER TABLE ADMIN.student_board ADD CONSTRAINT students_board_pk PRIMARY KEY ( sdt_email,
                                                                         bad_email );

CREATE TABLE ADMIN.task (
                      id          RAW(16) NOT NULL,
                      title       VARCHAR2(63) NOT NULL,
                      description VARCHAR2(255) NOT NULL,
                      created_at  TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL,
                      started_at  TIMESTAMP WITH TIME ZONE,
                      finished_at TIMESTAMP WITH TIME ZONE,
                      deadline    TIMESTAMP WITH TIME ZONE NOT NULL,
                      active     number DEFAULT 1 NOT NULL,
                      clr_NAME    VARCHAR2(15) NOT NULL
);

ALTER TABLE ADMIN.task ADD CONSTRAINT tasks_pk PRIMARY KEY ( id );

CREATE TABLE ADMIN.task_assignee (
                               tsk_id        RAW(16) NOT NULL,
                               sbd_sdt_email VARCHAR2(63 CHAR) NOT NULL,
                               sbd_bad_email VARCHAR2(63 CHAR) NOT NULL
);

ALTER TABLE ADMIN.task_assignee
    ADD CONSTRAINT relation_19_pk PRIMARY KEY ( tsk_id,
                                                sbd_sdt_email,
                                                sbd_bad_email );

CREATE TABLE ADMIN.task_attachement (
                                  fle_id RAW(16) NOT NULL,
                                  tsk_id RAW(16) NOT NULL
);

ALTER TABLE ADMIN.task_attachement ADD CONSTRAINT task_attachements_pk PRIMARY KEY ( fle_id );

CREATE TABLE ADMIN.task_cover (
                            fle_id RAW(16) NOT NULL,
                            tsk_id RAW(16) NOT NULL
);

ALTER TABLE ADMIN.task_cover ADD CONSTRAINT task_covers_pk PRIMARY KEY ( fle_id );

ALTER TABLE ADMIN.task_cover ADD CONSTRAINT task_covers_pkv1 UNIQUE ( tsk_id );

ALTER TABLE ADMIN.admin
    ADD CONSTRAINT admins_app_users_fk FOREIGN KEY ( email )
        REFERENCES ADMIN.app_user ( email );

ALTER TABLE ADMIN.board_stage
    ADD CONSTRAINT board_stages_boards_fk FOREIGN KEY ( bad_email )
        REFERENCES ADMIN.board ( mnr_email );

ALTER TABLE ADMIN.board_stage
    ADD CONSTRAINT board_stages_stages_fk FOREIGN KEY ( sae_NAME )
        REFERENCES ADMIN.stage ( NAME );

ALTER TABLE ADMIN.board
    ADD CONSTRAINT boards_managers_fk FOREIGN KEY ( mnr_email )
        REFERENCES ADMIN.manager ( email );

ALTER TABLE ADMIN.file_source
    ADD CONSTRAINT file_sources_files_fk FOREIGN KEY ( fle_id )
        REFERENCES ADMIN."FILE" ( id );

ALTER TABLE ADMIN.manager
    ADD CONSTRAINT managers_admins_fk FOREIGN KEY ( created_by )
        REFERENCES ADMIN.admin ( email );

ALTER TABLE ADMIN.manager
    ADD CONSTRAINT managers_app_users_fk FOREIGN KEY ( email )
        REFERENCES ADMIN.app_user ( email );

ALTER TABLE ADMIN.quarter_group
    ADD CONSTRAINT quarter_groups_academic_groups_fk FOREIGN KEY ( agp_NAME )
        REFERENCES ADMIN.academic_group ( NAME );

ALTER TABLE ADMIN.quarter_group
    ADD CONSTRAINT quarter_groups_academic_quarters_fk FOREIGN KEY ( aqr_number )
        REFERENCES ADMIN.academic_quarter ( "number" );

ALTER TABLE ADMIN.task_assignee
    ADD CONSTRAINT relation_19_students_board_fk
        FOREIGN KEY ( sbd_sdt_email,
                      sbd_bad_email )
            REFERENCES ADMIN.student_board ( sdt_email,
                                       bad_email );

ALTER TABLE ADMIN.task_assignee
    ADD CONSTRAINT relation_19_tasks_fk FOREIGN KEY ( tsk_id )
        REFERENCES ADMIN.task ( id );

ALTER TABLE ADMIN.stage_task
    ADD CONSTRAINT stage_tasks_board_stages_fk
        FOREIGN KEY ( bse_bad_email,
                      bse_sae_NAME )
            REFERENCES ADMIN.board_stage ( bad_email,
                                     sae_NAME );

ALTER TABLE ADMIN.stage_task
    ADD CONSTRAINT stage_tasks_tasks_fk FOREIGN KEY ( tsk_id )
        REFERENCES ADMIN.task ( id );

ALTER TABLE ADMIN.student
    ADD CONSTRAINT students_app_users_fk FOREIGN KEY ( email )
        REFERENCES ADMIN.app_user ( email );

ALTER TABLE ADMIN.student_board
    ADD CONSTRAINT students_board_boards_fk FOREIGN KEY ( bad_email )
        REFERENCES ADMIN.board ( mnr_email );

ALTER TABLE ADMIN.student_board
    ADD CONSTRAINT students_board_students_fk FOREIGN KEY ( sdt_email )
        REFERENCES ADMIN.student ( email );

ALTER TABLE ADMIN.student
    ADD CONSTRAINT students_managers_fk FOREIGN KEY ( created_by )
        REFERENCES ADMIN.manager ( email );

ALTER TABLE ADMIN.student
    ADD CONSTRAINT students_quarter_groups_fk
        FOREIGN KEY ( qgp_agp_NAME,
                      qgp_aqr_number )
            REFERENCES ADMIN.quarter_group ( agp_NAME,
                                       aqr_number );

ALTER TABLE ADMIN.task_attachement
    ADD CONSTRAINT task_attachements_files_fk FOREIGN KEY ( fle_id )
        REFERENCES ADMIN."FILE" ( id );

ALTER TABLE ADMIN.task_attachement
    ADD CONSTRAINT task_attachements_tasks_fk FOREIGN KEY ( tsk_id )
        REFERENCES ADMIN.task ( id );

ALTER TABLE ADMIN.task_cover
    ADD CONSTRAINT task_covers_files_fk FOREIGN KEY ( fle_id )
        REFERENCES ADMIN."FILE" ( id );

ALTER TABLE ADMIN.task_cover
    ADD CONSTRAINT task_covers_tasks_fk FOREIGN KEY ( tsk_id )
        REFERENCES ADMIN.task ( id );

ALTER TABLE ADMIN.task
    ADD CONSTRAINT tasks_COLORs_fk FOREIGN KEY ( clr_NAME )
        REFERENCES ADMIN.COLOR ( NAME );

CREATE OR REPLACE TRIGGER ADMIN.fkntm_board_stage BEFORE
UPDATE OF bad_email, sae_NAME ON ADMIN.board_stage
BEGIN
    raise_application_error(-20225, 'Non Transferable FK constraint  on table BOARD_STAGE is violated');
END;
/

CREATE OR REPLACE TRIGGER ADMIN.fkntm_manager BEFORE
UPDATE OF created_by ON ADMIN.manager
BEGIN
    raise_application_error(-20225, 'Non Transferable FK constraint  on table MANAGER is violated');
END;
/

CREATE OR REPLACE TRIGGER ADMIN.fkntm_student BEFORE
UPDATE OF created_by ON ADMIN.student
BEGIN
    raise_application_error(-20225, 'Non Transferable FK constraint  on table STUDENT is violated');
END;
/

CREATE OR REPLACE TRIGGER ADMIN.arc_fkarc_1_student BEFORE
INSERT OR UPDATE OF email ON ADMIN.student
    FOR EACH ROW
    DECLARE
    d VARCHAR2(15);
BEGIN
SELECT
    a.type
INTO d
FROM
    ADMIN.app_user a
WHERE
    a.email = :new.email;

IF ( d IS NULL
       OR d <> 'student' ) THEN
        raise_application_error(-20223, 'FK STUDENTS_APP_USERS_FK in Table STUDENT violates Arc constraint on Table APP_USER - discriminator column type doesn''t have value ''student'''
        );
END IF;

EXCEPTION
    WHEN no_data_found THEN
        NULL;
WHEN OTHERS THEN
        RAISE;
END;
/

CREATE OR REPLACE TRIGGER ADMIN.arc_fkarc_1_manager BEFORE
INSERT OR UPDATE OF email ON ADMIN.manager
    FOR EACH ROW
    DECLARE
    d VARCHAR2(15);
BEGIN
SELECT
    a.type
INTO d
FROM
    ADMIN.app_user a
WHERE
    a.email = :new.email;

IF ( d IS NULL
       OR d <> 'manager' ) THEN
        raise_application_error(-20223, 'FK MANAGERS_APP_USERS_FK in Table MANAGER violates Arc constraint on Table APP_USER - discriminator column type doesn''t have value ''manager'''
        );
END IF;

EXCEPTION
    WHEN no_data_found THEN
        NULL;
WHEN OTHERS THEN
        RAISE;
END;
/

CREATE OR REPLACE TRIGGER ADMIN.arc_fkarc_1_admin BEFORE
INSERT OR UPDATE OF email ON ADMIN.admin
    FOR EACH ROW
    DECLARE
    d VARCHAR2(15);
BEGIN
SELECT
    a.type
INTO d
FROM
    ADMIN.app_user a
WHERE
    a.email = :new.email;

IF ( d IS NULL
       OR d <> 'admin' ) THEN
        raise_application_error(-20223, 'FK ADMINS_APP_USERS_FK in Table ADMIN violates Arc constraint on Table APP_USER - discriminator column type doesn''t have value ''admin'''
        );
END IF;

EXCEPTION
    WHEN no_data_found THEN
        NULL;
WHEN OTHERS THEN
        RAISE;
END;
/

CREATE OR REPLACE TRIGGER ADMIN.arc_fkarc_2_task_cover BEFORE
INSERT OR UPDATE OF fle_id ON ADMIN.task_cover
    FOR EACH ROW
    DECLARE
    d VARCHAR2(15);
BEGIN
SELECT
    a.purpose
INTO d
FROM
    ADMIN."FILE" a
WHERE
    a.id = :new.fle_id;

IF ( d IS NULL
       OR d <> 'cover' ) THEN
        raise_application_error(-20223, 'FK TASK_COVERS_FILES_FK in Table TASK_COVER violates Arc constraint on Table "FILE" - discriminator column purpose doesn''t have value ''cover'''
        );
END IF;

EXCEPTION
    WHEN no_data_found THEN
        NULL;
WHEN OTHERS THEN
        RAISE;
END;
/

CREATE OR REPLACE TRIGGER ADMIN.arc_fkarc_2_task_attachement BEFORE
INSERT OR UPDATE OF fle_id ON ADMIN.task_attachement
    FOR EACH ROW
    DECLARE
    d VARCHAR2(15);
BEGIN
SELECT
    a.purpose
INTO d
FROM
    ADMIN."FILE" a
WHERE
    a.id = :new.fle_id;

IF ( d IS NULL
       OR d <> 'attachement' ) THEN
        raise_application_error(-20223, 'FK TASK_ATTACHEMENTS_FILES_FK in Table TASK_ATTACHEMENT violates Arc constraint on Table "FILE" - discriminator column purpose doesn''t have value ''attachement'''
        );
END IF;

EXCEPTION
    WHEN no_data_found THEN
        NULL;
WHEN OTHERS THEN
        RAISE;
END;
/

-- -----------------------------------------------------
-- Data for table COLOR
-- -----------------------------------------------------
MERGE INTO ADMIN.COLOR c USING (SELECT 'Red' AS NAME, '#FF0000' AS CODE FROM DUAL) src ON (c.NAME = src.NAME)
WHEN NOT MATCHED THEN INSERT (NAME, CODE) VALUES (src.NAME, src.CODE);

MERGE INTO ADMIN.COLOR c USING (SELECT 'Orange' AS NAME, '#F97316' AS CODE FROM DUAL) src ON (c.NAME = src.NAME)
WHEN NOT MATCHED THEN INSERT (NAME, CODE) VALUES (src.NAME, src.CODE);

MERGE INTO ADMIN.COLOR c USING (SELECT 'Amber' AS NAME, '#F59E0B' AS CODE FROM DUAL) src ON (c.NAME = src.NAME)
WHEN NOT MATCHED THEN INSERT (NAME, CODE) VALUES (src.NAME, src.CODE);

MERGE INTO ADMIN.COLOR c USING (SELECT 'Yellow' AS NAME, '#EAB308' AS CODE FROM DUAL) src ON (c.NAME = src.NAME)
WHEN NOT MATCHED THEN INSERT (NAME, CODE) VALUES (src.NAME, src.CODE);

MERGE INTO ADMIN.COLOR c USING (SELECT 'Lime' AS NAME, '#84CC16' AS CODE FROM DUAL) src ON (c.NAME = src.NAME)
WHEN NOT MATCHED THEN INSERT (NAME, CODE) VALUES (src.NAME, src.CODE);

MERGE INTO ADMIN.COLOR c USING (SELECT 'Green' AS NAME, '#22C55E' AS CODE FROM DUAL) src ON (c.NAME = src.NAME)
WHEN NOT MATCHED THEN INSERT (NAME, CODE) VALUES (src.NAME, src.CODE);

MERGE INTO ADMIN.COLOR c USING (SELECT 'Emerald' AS NAME, '#10B981' AS CODE FROM DUAL) src ON (c.NAME = src.NAME)
WHEN NOT MATCHED THEN INSERT (NAME, CODE) VALUES (src.NAME, src.CODE);

MERGE INTO ADMIN.COLOR c USING (SELECT 'Teal' AS NAME, '#14B8A6' AS CODE FROM DUAL) src ON (c.NAME = src.NAME)
WHEN NOT MATCHED THEN INSERT (NAME, CODE) VALUES (src.NAME, src.CODE);

MERGE INTO ADMIN.COLOR c USING (SELECT 'Cyan' AS NAME, '#06B6D4' AS CODE FROM DUAL) src ON (c.NAME = src.NAME)
WHEN NOT MATCHED THEN INSERT (NAME, CODE) VALUES (src.NAME, src.CODE);

MERGE INTO ADMIN.COLOR c USING (SELECT 'Blue' AS NAME, '#3B82F6' AS CODE FROM DUAL) src ON (c.NAME = src.NAME)
WHEN NOT MATCHED THEN INSERT (NAME, CODE) VALUES (src.NAME, src.CODE);

MERGE INTO ADMIN.COLOR c USING (SELECT 'Indigo' AS NAME, '#6366F1' AS CODE FROM DUAL) src ON (c.NAME = src.NAME)
WHEN NOT MATCHED THEN INSERT (NAME, CODE) VALUES (src.NAME, src.CODE);

MERGE INTO ADMIN.COLOR c USING (SELECT 'Violet' AS NAME, '#8B5CF6' AS CODE FROM DUAL) src ON (c.NAME = src.NAME)
WHEN NOT MATCHED THEN INSERT (NAME, CODE) VALUES (src.NAME, src.CODE);

MERGE INTO ADMIN.COLOR c USING (SELECT 'Fuchsia' AS NAME, '#D946EF' AS CODE FROM DUAL) src ON (c.NAME = src.NAME)
WHEN NOT MATCHED THEN INSERT (NAME, CODE) VALUES (src.NAME, src.CODE);

MERGE INTO ADMIN.COLOR c USING (SELECT 'Pink' AS NAME, '#EC4899' AS CODE FROM DUAL) src ON (c.NAME = src.NAME)
WHEN NOT MATCHED THEN INSERT (NAME, CODE) VALUES (src.NAME, src.CODE);

MERGE INTO ADMIN.COLOR c USING (SELECT 'Rose' AS NAME, '#F43F5E' AS CODE FROM DUAL) src ON (c.NAME = src.NAME)
WHEN NOT MATCHED THEN INSERT (NAME, CODE) VALUES (src.NAME, src.CODE);

MERGE INTO ADMIN.COLOR c USING (SELECT 'Gray' AS NAME, '#6B7280' AS CODE FROM DUAL) src ON (c.NAME = src.NAME)
WHEN NOT MATCHED THEN INSERT (NAME, CODE) VALUES (src.NAME, src.CODE);

MERGE INTO ADMIN.COLOR c USING (SELECT 'Slate' AS NAME, '#64748B' AS CODE FROM DUAL) src ON (c.NAME = src.NAME)
WHEN NOT MATCHED THEN INSERT (NAME, CODE) VALUES (src.NAME, src.CODE);

MERGE INTO ADMIN.COLOR c USING (SELECT 'Zinc' AS NAME, '#71717A' AS CODE FROM DUAL) src ON (c.NAME = src.NAME)
WHEN NOT MATCHED THEN INSERT (NAME, CODE) VALUES (src.NAME, src.CODE);

-- -----------------------------------------------------
-- Data for table stage
-- -----------------------------------------------------
MERGE INTO ADMIN.stage s USING (SELECT 'To Do' AS NAME, 0 AS final FROM DUAL) src ON (s.NAME = src.NAME)
WHEN NOT MATCHED THEN INSERT (NAME, final) VALUES (src.NAME, src.final);

MERGE INTO ADMIN.stage s USING (SELECT 'In Progress' AS NAME, 0 AS final FROM DUAL) src ON (s.NAME = src.NAME)
WHEN NOT MATCHED THEN INSERT (NAME, final) VALUES (src.NAME, src.final);

MERGE INTO ADMIN.stage s USING (SELECT 'Done' AS NAME, 1 AS final FROM DUAL) src ON (s.NAME = src.NAME)
WHEN NOT MATCHED THEN INSERT (NAME, final) VALUES (src.NAME, src.final);

